const carData = [
  {
    car_id: 'clm0umzcs0000tcrff751inoy',
    car_name: 'Ford Fusion',
    car_type: 'Sedan',
    car_img: '/cars/5.png',
    car_details: {
      seats: 5,
      luggage: 2,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs0001tcrf64n478cw',
    car_name: 'Suzuki Vitara',
    car_type: 'SUV',
    car_img: '/cars/6.png',
    car_details: {
      seats: 5,
      luggage: 2,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs0002tcrfybhtzuas',
    car_name: 'Volkswagen Up',
    car_type: 'Hatchback',
    car_img: '/cars/7.png',
    car_details: {
      seats: 5,
      luggage: 2,
      air_conditioner: false,
      transmition: 'manual',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs0003tcrfaid5fwlg',
    car_name: 'Honda Accord',
    car_type: 'Sedan',
    car_img: '/cars/8.png',
    car_details: {
      seats: 5,
      luggage: 2,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs0004tcrf1g978i3a',
    car_name: 'Force Traveller',
    car_type: 'Camper',
    car_img: '/cars/9.png',
    car_details: {
      seats: 9,
      luggage: 4,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs0005tcrfhgkuymua',
    car_name: 'Land Rove Evoque',
    car_type: 'SUV',
    car_img: '/cars/10.png',
    car_details: {
      seats: 5,
      luggage: 4,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs0006tcrffkivccc8',
    car_name: 'BMW i8 2018',
    car_type: 'Luxury Coupe',
    car_img: '/cars/11.png',
    car_details: {
      seats: 2,
      luggage: 2,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 8,
    car_name: 'Tesla Model 3',
    car_type: 'Electric Sedan',
    car_img: '/cars/12.png',
    car_details: {
      seats: 5,
      luggage: 2,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs0007tcrfxdnh3l60',
    car_name: 'BMW i4',
    car_type: 'Electric Sedan',
    car_img: '/cars/13.png',
    car_details: {
      seats: 5,
      luggage: 2,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs0009tcrfel6hiyih',
    car_name: 'Renault Kwid',
    car_type: 'Hatchback',
    car_img: '/cars/14.png',
    car_details: {
      seats: 5,
      luggage: 1,
      air_conditioner: true,
      transmition: 'manual',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs000atcrfi820r6or',
    car_name: 'Seat Leon',
    car_type: 'Hatchback',
    car_img: '/cars/15.png',
    car_details: {
      seats: 5,
      luggage: 1,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
  {
    car_id: 'clm0umzcs000btcrf83gyvcp7',
    car_name: 'Volkswagen Transporter',
    car_type: 'Van',
    car_img: '/cars/16.png',
    car_details: {
      seats: 9,
      luggage: 4,
      air_conditioner: true,
      transmition: 'automatic',
    },
    fare_km: 2500,
  },
];

export default carData;
